# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ambilight.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61mbilight.proto\"\xae\x04\n\x07Message\x12\x1c\n\x06sender\x18\x01 \x01(\x0e\x32\x07.SenderH\x00\x88\x01\x01\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x0c.MessageTypeH\x01\x88\x01\x01\x12\x1c\n\x0fsequence_number\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x16\n\ttimestamp\x18\x04 \x01(\x03H\x03\x88\x01\x01\x12$\n\x06\x63onfig\x18\x05 \x01(\x0b\x32\x0f.Message.ConfigH\x04\x88\x01\x01\x12 \n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\r.Message.DataH\x05\x88\x01\x01\x1a\x98\x01\n\x06\x43onfig\x12\x11\n\x04ipv4\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04port\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x08num_leds\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12#\n\nled_format\x18\x04 \x01(\x0e\x32\n.LedFormatH\x03\x88\x01\x01\x42\x07\n\x05_ipv4B\x07\n\x05_portB\x0b\n\t_num_ledsB\r\n\x0b_led_format\x1a\x80\x01\n\x04\x44\x61ta\x12\x15\n\x08led_data\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x18\n\x0bled_palette\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x19\n\x0cled_position\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x0b\n\t_led_dataB\x0e\n\x0c_led_paletteB\x0f\n\r_led_positionB\t\n\x07_senderB\x07\n\x05_typeB\x12\n\x10_sequence_numberB\x0c\n\n_timestampB\t\n\x07_configB\x07\n\x05_data*g\n\x0bMessageType\x12\x11\n\rACK_DISCOVERY\x10\x00\x12\r\n\tDISCOVERY\x10\x01\x12\n\n\x06\x43ONFIG\x10\x02\x12\x08\n\x04\x44\x41TA\x10\x03\x12\r\n\tHEARTBEAT\x10\x04\x12\x11\n\rACK_HEARTBEAT\x10\x05*?\n\x06Sender\x12\n\n\x06SERVER\x10\x00\x12\x14\n\x10\x43LIENT_AMBILIGHT\x10\x01\x12\x13\n\x0f\x43LIENT_AUDIOBOX\x10\x02*;\n\tLedFormat\x12\x13\n\x0fSERPENTINE_GRID\x10\x00\x12\x19\n\x15RECTANGULAR_PERIMETER\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ambilight_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=580
  _MESSAGETYPE._serialized_end=683
  _SENDER._serialized_start=685
  _SENDER._serialized_end=748
  _LEDFORMAT._serialized_start=750
  _LEDFORMAT._serialized_end=809
  _MESSAGE._serialized_start=20
  _MESSAGE._serialized_end=578
  _MESSAGE_CONFIG._serialized_start=221
  _MESSAGE_CONFIG._serialized_end=373
  _MESSAGE_DATA._serialized_start=376
  _MESSAGE_DATA._serialized_end=504
# @@protoc_insertion_point(module_scope)
